on: push
name: Image Build
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: login
      uses: actions/docker/login@c08a5fc9e0286844156fefff2c141072048141f6
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: build
      uses: actions/docker/cli@c08a5fc9e0286844156fefff2c141072048141f6
      with:
        args: build -t chim .
    - name: tag
      uses: actions/docker/tag@master
      with:
        args: -l -s chim keyglitch/chim
    - name: push
      uses: actions/docker/cli@c08a5fc9e0286844156fefff2c141072048141f6
      with:
        args: push keyglitch/chim
